Repository sergej0071/RRMS, pull requests merged in 2023-02, with the labels that each got.

#154 do fix
  backend/rrms_scheduler_app/apps.py
  backend/rrms_scheduler_app/scheduler.py
Labels: hotfix

#155 do fix
  backend/rrms_scheduler_app/scheduler.py
  backend/rrms_web_app/migrations/0001_initial.py
  backend/rrms_web_app/models.py
  backend/rrms_web_app/views.py
Labels: hotfix

#156 do fix
  backend/rrms_scheduler_app/scheduler.py
  backend/rrms_web_app/migrations/0001_initial.py
  backend/rrms_web_app/models.py
  backend/rrms_web_app/tests/test_views.py
  backend/rrms_web_app/urls.py
  backend/rrms_web_app/views.py
Labels: hotfix

#162 Feature/rrms 111 added new functionality for lab5 d 1
  backend/rrms_arduino_app/arduinoService.py
  backend/rrms_scheduler_app/services/dataExplorationService.py
  backend/rrms_scheduler_app/services/predictionService.py
  backend/rrms_web_app/urls.py
  backend/rrms_web_app/viewHelpers/dataMapperHelper.py
  backend/rrms_web_app/viewHelpers/genericORMaRepository.py
  backend/rrms_web_app/views.py
Labels: feature

#163 RRMS-112: initialization analysis-page
  frontend/src/app/app-routing.module.ts
  frontend/src/app/content/analysis-page/analysis-page.component.html
  frontend/src/app/content/analysis-page/analysis-page.component.scss
  frontend/src/app/content/analysis-page/analysis-page.component.ts
  frontend/src/app/content/content.module.ts
  frontend/src/app/content/current-page/current-page.component.html
  frontend/src/app/content/statistic-page/statistic-page.component.html
  frontend/src/app/header/header.component.ts
  frontend/src/app/shared/interfaces.ts
  frontend/src/app/shared/services/parse-api.service.ts
Labels: feature

#164 RRMS-112: fix naming model.
  backend/rrms_scheduler_app/scheduler.py
  backend/rrms_web_app/migrations/0001_initial.py
  backend/rrms_web_app/models.py
  backend/rrms_web_app/tests/test_models.py
  backend/rrms_web_app/viewHelpers/genericORMaRepository.py
Labels: bugfix

#165 RRMS-113: Added localization on analysis-page
  frontend/src/app/shared/articles.ts
  frontend/src/assets/i18n/en.json
  frontend/src/assets/i18n/ru.json
  frontend/src/assets/i18n/ua.json
Labels: feature

#166 RRMS-114: probability charts
  frontend/src/app/content/analysis-page/analysis-page.component.html
  frontend/src/app/content/analysis-page/analysis-page.component.ts
  frontend/src/app/shared/interfaces.ts
  frontend/src/app/shared/services/parse-api.service.ts
Labels: feature

#168 Create README.md
  backend/README.md
Labels: hotfix

#167 RRMS-115: Add correlation charts
  frontend/src/app/content/analysis-page/analysis-page.component.html
  frontend/src/app/content/analysis-page/analysis-page.component.ts
  frontend/src/app/shared/interfaces.ts
  frontend/src/app/shared/services/parse-api.service.ts
Labels: feature

#176 Create README.md
  backend/README.md
Labels: hotfix

#177 RRMS-74: Do mock for sheduler
  backend/rrms_project/settings.py
  backend/rrms_scheduler_app/scheduler.py
  backend/rrms_web_app/migrations/0001_initial.py
Labels: feature
